package cm.gov.minfof.model.entity.common.serviceinterface;

import cm.gov.minfof.model.entity.common.FamillePfnlViewSDO;
import cm.gov.minfof.model.entity.common.PartiesProduitsPfnlViewSDO;
import cm.gov.minfof.model.entity.common.PartiesRecolteesViewSDO;
import cm.gov.minfof.model.entity.common.ProduitsPfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.AgrementsViewSDO;
import cm.gov.minfof.model.entityviewobject.common.CategorieproduitViewSDO;
import cm.gov.minfof.model.entityviewobject.common.CategorieunitemesureViewSDO;
import cm.gov.minfof.model.entityviewobject.common.CollectepfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DepartementViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DetailpermisViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DetailscollectepfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DetailsexportpfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.ExportpfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.LettrevoitureViewSDO;
import cm.gov.minfof.model.entityviewobject.common.LocaliteViewSDO;
import cm.gov.minfof.model.entityviewobject.common.OriginespnflsViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PartiproduitSDO;
import cm.gov.minfof.model.entityviewobject.common.PaysViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PermisViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PermissionnairespnflViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PostecontroleViewSDO;
import cm.gov.minfof.model.entityviewobject.common.RegionViewSDO;
import cm.gov.minfof.model.entityviewobject.common.TransporteurViewSDO;
import cm.gov.minfof.model.entityviewobject.common.TypevehiculeViewSDO;
import cm.gov.minfof.model.entityviewobject.common.UnitemesureViewSDO;
import cm.gov.minfof.model.entityviewobject.common.VehiculeViewSDO;
import cm.gov.minfof.model.queryviewobject.common.CommunesViewSDO;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 21 09:13:39 CET 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/cm/gov/minfof/model/entity/common/", name = "pfnl_wbs",
                    wsdlLocation = "cm/gov/minfof/model/entity/common/serviceinterface/pfnl_wbs.wsdl")
@SDODatabinding(schemaLocation = "cm/gov/minfof/model/entity/common/serviceinterface/pfnl_wbs.xsd")
public interface pfnl_wbs {


    public static final String NAME = "{/cm/gov/minfof/model/entity/common/}pfnl_wbs";

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getAgrementsView1", operationName = "getAgrementsView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getAgrementsView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getAgrementsView1Response")
    @WebResult(name = "result")
    AgrementsViewSDO getAgrementsView1(@WebParam(mode = WebParam.Mode.IN, name = "idagrements")
                                       BigDecimal idagrements) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findAgrementsView1", operationName = "findAgrementsView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findAgrementsView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findAgrementsView1Response")
    @WebResult(name = "result")
    List<AgrementsViewSDO> findAgrementsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                              FindCriteria findCriteria,
                                              @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                              FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getCategorieproduitView1",
               operationName = "getCategorieproduitView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "getCategorieproduitView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getCategorieproduitView1Response")
    @WebResult(name = "result")
    CategorieproduitViewSDO getCategorieproduitView1(@WebParam(mode = WebParam.Mode.IN, name = "idcategorieproduit")
                                                     BigDecimal idcategorieproduit) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findCategorieproduitView1",
               operationName = "findCategorieproduitView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "findCategorieproduitView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findCategorieproduitView1Response")
    @WebResult(name = "result")
    List<CategorieproduitViewSDO> findCategorieproduitView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                            FindCriteria findCriteria,
                                                            @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                            FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getCategorieunitemesureView1",
               operationName = "getCategorieunitemesureView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "getCategorieunitemesureView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getCategorieunitemesureView1Response")
    @WebResult(name = "result")
    CategorieunitemesureViewSDO getCategorieunitemesureView1(@WebParam(mode = WebParam.Mode.IN,
                                                                       name = "idcategorieunitemesure")
                                                             BigDecimal idcategorieunitemesure) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findCategorieunitemesureView1",
               operationName = "findCategorieunitemesureView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "findCategorieunitemesureView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findCategorieunitemesureView1Response")
    @WebResult(name = "result")
    List<CategorieunitemesureViewSDO> findCategorieunitemesureView1(@WebParam(mode = WebParam.Mode.IN,
                                                                              name = "findCriteria")
                                                                    FindCriteria findCriteria,
                                                                    @WebParam(mode = WebParam.Mode.IN,
                                                                              name = "findControl")
                                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getCollectepfnlView1",
               operationName = "getCollectepfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getCollectepfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getCollectepfnlView1Response")
    @WebResult(name = "result")
    CollectepfnlViewSDO getCollectepfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "idcollectepfnl")
                                             BigDecimal idcollectepfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findCollectepfnlView1",
               operationName = "findCollectepfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findCollectepfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findCollectepfnlView1Response")
    @WebResult(name = "result")
    List<CollectepfnlViewSDO> findCollectepfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getCommunesView1", operationName = "getCommunesView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getCommunesView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getCommunesView1Response")
    @WebResult(name = "result")
    CommunesViewSDO getCommunesView1(@WebParam(mode = WebParam.Mode.IN, name = "idcommunes")
                                     BigDecimal idcommunes) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findCommunesView1", operationName = "findCommunesView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findCommunesView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findCommunesView1Response")
    @WebResult(name = "result")
    List<CommunesViewSDO> findCommunesView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                            FindCriteria findCriteria,
                                            @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                            FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getDepartementView1", operationName = "getDepartementView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getDepartementView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getDepartementView1Response")
    @WebResult(name = "result")
    DepartementViewSDO getDepartementView1(@WebParam(mode = WebParam.Mode.IN, name = "iddepartements")
                                           BigDecimal iddepartements) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findDepartementView1",
               operationName = "findDepartementView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findDepartementView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findDepartementView1Response")
    @WebResult(name = "result")
    List<DepartementViewSDO> findDepartementView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                  FindCriteria findCriteria,
                                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getDetailpermisView1",
               operationName = "getDetailpermisView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getDetailpermisView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getDetailpermisView1Response")
    @WebResult(name = "result")
    DetailpermisViewSDO getDetailpermisView1(@WebParam(mode = WebParam.Mode.IN, name = "iddetailpermis")
                                             BigDecimal iddetailpermis) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findDetailpermisView1",
               operationName = "findDetailpermisView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findDetailpermisView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findDetailpermisView1Response")
    @WebResult(name = "result")
    List<DetailpermisViewSDO> findDetailpermisView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getDetailscollectepfnlView1",
               operationName = "getDetailscollectepfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "getDetailscollectepfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getDetailscollectepfnlView1Response")
    @WebResult(name = "result")
    DetailscollectepfnlViewSDO getDetailscollectepfnlView1(@WebParam(mode = WebParam.Mode.IN,
                                                                     name = "iddetailscollectepfnl")
                                                           BigDecimal iddetailscollectepfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findDetailscollectepfnlView1",
               operationName = "findDetailscollectepfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "findDetailscollectepfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findDetailscollectepfnlView1Response")
    @WebResult(name = "result")
    List<DetailscollectepfnlViewSDO> findDetailscollectepfnlView1(@WebParam(mode = WebParam.Mode.IN,
                                                                            name = "findCriteria")
                                                                  FindCriteria findCriteria,
                                                                  @WebParam(mode = WebParam.Mode.IN,
                                                                            name = "findControl")
                                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getDetailsexportpfnlView1",
               operationName = "getDetailsexportpfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "getDetailsexportpfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getDetailsexportpfnlView1Response")
    @WebResult(name = "result")
    DetailsexportpfnlViewSDO getDetailsexportpfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "iddetailsexportpfnl")
                                                       BigDecimal iddetailsexportpfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findDetailsexportpfnlView1",
               operationName = "findDetailsexportpfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "findDetailsexportpfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findDetailsexportpfnlView1Response")
    @WebResult(name = "result")
    List<DetailsexportpfnlViewSDO> findDetailsexportpfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                              FindCriteria findCriteria,
                                                              @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                              FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getExportpfnlView1", operationName = "getExportpfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getExportpfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getExportpfnlView1Response")
    @WebResult(name = "result")
    ExportpfnlViewSDO getExportpfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "idexportpfnl")
                                         BigDecimal idexportpfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findExportpfnlView1", operationName = "findExportpfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findExportpfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findExportpfnlView1Response")
    @WebResult(name = "result")
    List<ExportpfnlViewSDO> findExportpfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                FindCriteria findCriteria,
                                                @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getFamillePfnlView1", operationName = "getFamillePfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getFamillePfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getFamillePfnlView1Response")
    @WebResult(name = "result")
    FamillePfnlViewSDO getFamillePfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "idfamillepfnl")
                                           BigDecimal idfamillepfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findFamillePfnlView1",
               operationName = "findFamillePfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findFamillePfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findFamillePfnlView1Response")
    @WebResult(name = "result")
    List<FamillePfnlViewSDO> findFamillePfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                  FindCriteria findCriteria,
                                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getLettrevoitureView1",
               operationName = "getLettrevoitureView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getLettrevoitureView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getLettrevoitureView1Response")
    @WebResult(name = "result")
    LettrevoitureViewSDO getLettrevoitureView1(@WebParam(mode = WebParam.Mode.IN, name = "idlettrevoiture")
                                               BigDecimal idlettrevoiture) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findLettrevoitureView1",
               operationName = "findLettrevoitureView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findLettrevoitureView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findLettrevoitureView1Response")
    @WebResult(name = "result")
    List<LettrevoitureViewSDO> findLettrevoitureView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                      FindCriteria findCriteria,
                                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                      FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getLocaliteView1", operationName = "getLocaliteView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getLocaliteView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getLocaliteView1Response")
    @WebResult(name = "result")
    LocaliteViewSDO getLocaliteView1(@WebParam(mode = WebParam.Mode.IN, name = "idlocalite")
                                     BigDecimal idlocalite) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findLocaliteView1", operationName = "findLocaliteView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findLocaliteView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findLocaliteView1Response")
    @WebResult(name = "result")
    List<LocaliteViewSDO> findLocaliteView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                            FindCriteria findCriteria,
                                            @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                            FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getOriginespnflsView1",
               operationName = "getOriginespnflsView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getOriginespnflsView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getOriginespnflsView1Response")
    @WebResult(name = "result")
    OriginespnflsViewSDO getOriginespnflsView1(@WebParam(mode = WebParam.Mode.IN, name = "idoriginespnfls")
                                               BigDecimal idoriginespnfls) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findOriginespnflsView1",
               operationName = "findOriginespnflsView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findOriginespnflsView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findOriginespnflsView1Response")
    @WebResult(name = "result")
    List<OriginespnflsViewSDO> findOriginespnflsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                      FindCriteria findCriteria,
                                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                      FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getPartiesProduitsPfnlView1",
               operationName = "getPartiesProduitsPfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "getPartiesProduitsPfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getPartiesProduitsPfnlView1Response")
    @WebResult(name = "result")
    PartiesProduitsPfnlViewSDO getPartiesProduitsPfnlView1(@WebParam(mode = WebParam.Mode.IN,
                                                                     name = "idpartiesproduitspfnl")
                                                           BigDecimal idpartiesproduitspfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findPartiesProduitsPfnlView1",
               operationName = "findPartiesProduitsPfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "findPartiesProduitsPfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findPartiesProduitsPfnlView1Response")
    @WebResult(name = "result")
    List<PartiesProduitsPfnlViewSDO> findPartiesProduitsPfnlView1(@WebParam(mode = WebParam.Mode.IN,
                                                                            name = "findCriteria")
                                                                  FindCriteria findCriteria,
                                                                  @WebParam(mode = WebParam.Mode.IN,
                                                                            name = "findControl")
                                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getPartiesRecolteesView1",
               operationName = "getPartiesRecolteesView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "getPartiesRecolteesView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getPartiesRecolteesView1Response")
    @WebResult(name = "result")
    PartiesRecolteesViewSDO getPartiesRecolteesView1(@WebParam(mode = WebParam.Mode.IN, name = "idpartiesrecoltees")
                                                     BigDecimal idpartiesrecoltees) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findPartiesRecolteesView1",
               operationName = "findPartiesRecolteesView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "findPartiesRecolteesView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findPartiesRecolteesView1Response")
    @WebResult(name = "result")
    List<PartiesRecolteesViewSDO> findPartiesRecolteesView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                            FindCriteria findCriteria,
                                                            @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                            FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getPartiproduit1", operationName = "getPartiproduit1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getPartiproduit1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getPartiproduit1Response")
    @WebResult(name = "result")
    PartiproduitSDO getPartiproduit1(@WebParam(mode = WebParam.Mode.IN, name = "idpartiesproduitspfnl")
                                     BigDecimal idpartiesproduitspfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findPartiproduit1", operationName = "findPartiproduit1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findPartiproduit1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findPartiproduit1Response")
    @WebResult(name = "result")
    List<PartiproduitSDO> findPartiproduit1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                            FindCriteria findCriteria,
                                            @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                            FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getPaysView1", operationName = "getPaysView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getPaysView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getPaysView1Response")
    @WebResult(name = "result")
    PaysViewSDO getPaysView1(@WebParam(mode = WebParam.Mode.IN, name = "idpays")
                             BigDecimal idpays) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findPaysView1", operationName = "findPaysView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findPaysView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findPaysView1Response")
    @WebResult(name = "result")
    List<PaysViewSDO> findPaysView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria") FindCriteria findCriteria,
                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getPermisView1", operationName = "getPermisView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getPermisView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getPermisView1Response")
    @WebResult(name = "result")
    PermisViewSDO getPermisView1(@WebParam(mode = WebParam.Mode.IN, name = "idpermis")
                                 BigDecimal idpermis) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findPermisView1", operationName = "findPermisView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findPermisView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findPermisView1Response")
    @WebResult(name = "result")
    List<PermisViewSDO> findPermisView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                        FindCriteria findCriteria,
                                        @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                        FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getPermissionnairespnflView1",
               operationName = "getPermissionnairespnflView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "getPermissionnairespnflView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getPermissionnairespnflView1Response")
    @WebResult(name = "result")
    PermissionnairespnflViewSDO getPermissionnairespnflView1(@WebParam(mode = WebParam.Mode.IN,
                                                                       name = "idpermissionnairespnfl")
                                                             BigDecimal idpermissionnairespnfl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findPermissionnairespnflView1",
               operationName = "findPermissionnairespnflView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                    localName = "findPermissionnairespnflView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findPermissionnairespnflView1Response")
    @WebResult(name = "result")
    List<PermissionnairespnflViewSDO> findPermissionnairespnflView1(@WebParam(mode = WebParam.Mode.IN,
                                                                              name = "findCriteria")
                                                                    FindCriteria findCriteria,
                                                                    @WebParam(mode = WebParam.Mode.IN,
                                                                              name = "findControl")
                                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getPostecontroleView1",
               operationName = "getPostecontroleView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getPostecontroleView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getPostecontroleView1Response")
    @WebResult(name = "result")
    PostecontroleViewSDO getPostecontroleView1(@WebParam(mode = WebParam.Mode.IN, name = "idpostecontrole")
                                               BigDecimal idpostecontrole) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findPostecontroleView1",
               operationName = "findPostecontroleView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findPostecontroleView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findPostecontroleView1Response")
    @WebResult(name = "result")
    List<PostecontroleViewSDO> findPostecontroleView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                      FindCriteria findCriteria,
                                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                      FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getProduitsPfnlView1",
               operationName = "getProduitsPfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getProduitsPfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getProduitsPfnlView1Response")
    @WebResult(name = "result")
    ProduitsPfnlViewSDO getProduitsPfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "idproduitspfnl")
                                             BigDecimal idproduitspfnl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findProduitsPfnlView1",
               operationName = "findProduitsPfnlView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findProduitsPfnlView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findProduitsPfnlView1Response")
    @WebResult(name = "result")
    List<ProduitsPfnlViewSDO> findProduitsPfnlView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getRegionView1", operationName = "getRegionView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getRegionView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getRegionView1Response")
    @WebResult(name = "result")
    RegionViewSDO getRegionView1(@WebParam(mode = WebParam.Mode.IN, name = "idregions")
                                 BigDecimal idregions) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findRegionView1", operationName = "findRegionView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findRegionView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findRegionView1Response")
    @WebResult(name = "result")
    List<RegionViewSDO> findRegionView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                        FindCriteria findCriteria,
                                        @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                        FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getTransporteurView1",
               operationName = "getTransporteurView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getTransporteurView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getTransporteurView1Response")
    @WebResult(name = "result")
    TransporteurViewSDO getTransporteurView1(@WebParam(mode = WebParam.Mode.IN, name = "idtransporteur")
                                             BigDecimal idtransporteur) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findTransporteurView1",
               operationName = "findTransporteurView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findTransporteurView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findTransporteurView1Response")
    @WebResult(name = "result")
    List<TransporteurViewSDO> findTransporteurView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getTypevehiculeView1",
               operationName = "getTypevehiculeView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getTypevehiculeView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getTypevehiculeView1Response")
    @WebResult(name = "result")
    TypevehiculeViewSDO getTypevehiculeView1(@WebParam(mode = WebParam.Mode.IN, name = "idtypevehicule")
                                             BigDecimal idtypevehicule) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findTypevehiculeView1",
               operationName = "findTypevehiculeView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findTypevehiculeView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findTypevehiculeView1Response")
    @WebResult(name = "result")
    List<TypevehiculeViewSDO> findTypevehiculeView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getUnitemesureView1", operationName = "getUnitemesureView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getUnitemesureView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getUnitemesureView1Response")
    @WebResult(name = "result")
    UnitemesureViewSDO getUnitemesureView1(@WebParam(mode = WebParam.Mode.IN, name = "idunitemesure")
                                           BigDecimal idunitemesure) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findUnitemesureView1",
               operationName = "findUnitemesureView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findUnitemesureView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findUnitemesureView1Response")
    @WebResult(name = "result")
    List<UnitemesureViewSDO> findUnitemesureView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                  FindCriteria findCriteria,
                                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/getVehiculeView1", operationName = "getVehiculeView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "getVehiculeView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "getVehiculeView1Response")
    @WebResult(name = "result")
    VehiculeViewSDO getVehiculeView1(@WebParam(mode = WebParam.Mode.IN, name = "idvehicule")
                                     BigDecimal idvehicule) throws ServiceException;

    @WebMethod(action = "/cm/gov/minfof/model/entity/common/findVehiculeView1", operationName = "findVehiculeView1")
    @RequestWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/", localName = "findVehiculeView1")
    @ResponseWrapper(targetNamespace = "/cm/gov/minfof/model/entity/common/types/",
                     localName = "findVehiculeView1Response")
    @WebResult(name = "result")
    List<VehiculeViewSDO> findVehiculeView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                            FindCriteria findCriteria,
                                            @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                            FindControl findControl) throws ServiceException;


}

