package cm.gov.minfof.model.entity.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 05 12:49:30 WAT 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    BigDecimal creerIdRegion();
}

