package cm.gov.minfof.model.entity;

import cm.gov.minfof.model.entity.common.AppModule;
import cm.gov.minfof.model.entityviewobject.RegionViewImpl;

import cm.gov.minfof.model.entityviewobject.gestLastIdUnitMesureImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdCategorieMesureImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdCategorieUniteMesureImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdCommunesImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdDepartementsImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdFamillesImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdOriginePfnlImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdPartiesRecolteesImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdPaysImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdPermissionnairePfnlImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdProduitsImpl;
import cm.gov.minfof.model.entityviewobject.getLastIdRegionsImpl;

import cm.gov.minfof.model.entityviewobject.getLastIdartiesProduitsPfnlImpl;

import cm.gov.minfof.model.entityviewobject.listeExploitantImpl;
import cm.gov.minfof.model.entityviewobject.listeOrigineImpl;

import cm.gov.minfof.model.entityviewobject.listeQualitePermissionnaireImpl;

import cm.gov.minfof.model.entityviewobject.listeSexeImpl;
import cm.gov.minfof.model.entityviewobject.listeStatutPermissionnaireImpl;
import cm.gov.minfof.model.entityviewobject.listeTypePersonneImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 05 11:35:57 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    
    
    
    /**
     * @return
     */
    public BigDecimal creerIdRegion() {
        BigDecimal lastId=new BigDecimal(0);
        getLastIdRegionsImpl vo = this.getgetLastIdRegions1();
        vo.executeQuery();
        if (vo.hasNext()) {
            Row r = vo.next();
            lastId = (BigDecimal) r.getAttribute(0);
            System.out.println("lastid = " + lastId);
        }
        BigDecimal un = new BigDecimal(1);
        lastId = lastId.add(un);
        return lastId;
    }
    
    /**
     * Container's getter for CommuneView1.
     * @return CommuneView1
     */
    public ViewObjectImpl getCommuneView1() {
        return (ViewObjectImpl) findViewObject("CommuneView1");
    }

    /**
     * Container's getter for DepartementView1.
     * @return DepartementView1
     */
    public ViewObjectImpl getDepartementView1() {
        return (ViewObjectImpl) findViewObject("DepartementView1");
    }

    /**
     * Container's getter for RegionView1.
     * @return RegionView1
     */
    public RegionViewImpl getRegionView1() {
        return (RegionViewImpl) findViewObject("RegionView1");
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public ViewObjectImpl getRegionsView1() {
        return (ViewObjectImpl) findViewObject("RegionsView1");
    }

    /**
     * Container's getter for CommunesView1.
     * @return CommunesView1
     */
    public ViewObjectImpl getCommunesView1() {
        return (ViewObjectImpl) findViewObject("CommunesView1");
    }

    /**
     * Container's getter for DepartementsView1.
     * @return DepartementsView1
     */
    public ViewObjectImpl getDepartementsView1() {
        return (ViewObjectImpl) findViewObject("DepartementsView1");
    }

    /**
     * Container's getter for DepartementView2.
     * @return DepartementView2
     */
    public ViewObjectImpl getDepartementView2() {
        return (ViewObjectImpl) findViewObject("DepartementView2");
    }

    /**
     * Container's getter for DepartementView3.
     * @return DepartementView3
     */
    public ViewObjectImpl getDepartementView3() {
        return (ViewObjectImpl) findViewObject("DepartementView3");
    }

    /**
     * Container's getter for CommuneView2.
     * @return CommuneView2
     */
    public ViewObjectImpl getCommuneView2() {
        return (ViewObjectImpl) findViewObject("CommuneView2");
    }

    /**
     * Container's getter for DepartementView4.
     * @return DepartementView4
     */
    public ViewObjectImpl getDepartementView4() {
        return (ViewObjectImpl) findViewObject("DepartementView4");
    }

    /**
     * Container's getter for CommuneView3.
     * @return CommuneView3
     */
    public ViewObjectImpl getCommuneView3() {
        return (ViewObjectImpl) findViewObject("CommuneView3");
    }

    /**
     * Container's getter for CommuneView4.
     * @return CommuneView4
     */
    public ViewObjectImpl getCommuneView4() {
        return (ViewObjectImpl) findViewObject("CommuneView4");
    }

    /**
     * Container's getter for CommunesView2.
     * @return CommunesView2
     */
    public ViewObjectImpl getCommunesView2() {
        return (ViewObjectImpl) findViewObject("CommunesView2");
    }

    /**
     * Container's getter for DepartementsView2.
     * @return DepartementsView2
     */
    public ViewObjectImpl getDepartementsView2() {
        return (ViewObjectImpl) findViewObject("DepartementsView2");
    }

    /**
     * Container's getter for CommunesView3.
     * @return CommunesView3
     */
    public ViewObjectImpl getCommunesView3() {
        return (ViewObjectImpl) findViewObject("CommunesView3");
    }

    /**
     * Container's getter for DepartementsView3.
     * @return DepartementsView3
     */
    public ViewObjectImpl getDepartementsView3() {
        return (ViewObjectImpl) findViewObject("DepartementsView3");
    }

    /**
     * Container's getter for CommunesView4.
     * @return CommunesView4
     */
    public ViewObjectImpl getCommunesView4() {
        return (ViewObjectImpl) findViewObject("CommunesView4");
    }

    /**
     * Container's getter for DepartementsView4.
     * @return DepartementsView4
     */
    public ViewObjectImpl getDepartementsView4() {
        return (ViewObjectImpl) findViewObject("DepartementsView4");
    }

    /**
     * Container's getter for CommuneView5.
     * @return CommuneView5
     */
    public ViewObjectImpl getCommuneView5() {
        return (ViewObjectImpl) findViewObject("CommuneView5");
    }

    /**
     * Container's getter for FamillePfnlView1.
     * @return FamillePfnlView1
     */
    public ViewObjectImpl getFamillePfnlView1() {
        return (ViewObjectImpl) findViewObject("FamillePfnlView1");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView1.
     * @return PartiesProduitsPfnlView1
     */
    public ViewObjectImpl getPartiesProduitsPfnlView1() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView1");
    }

    /**
     * Container's getter for PartiesRecolteesView1.
     * @return PartiesRecolteesView1
     */
    public ViewObjectImpl getPartiesRecolteesView1() {
        return (ViewObjectImpl) findViewObject("PartiesRecolteesView1");
    }

    /**
     * Container's getter for ProduitsPfnlView1.
     * @return ProduitsPfnlView1
     */
    public ViewObjectImpl getProduitsPfnlView1() {
        return (ViewObjectImpl) findViewObject("ProduitsPfnlView1");
    }

    /**
     * Container's getter for ProduitspfnlView2.
     * @return ProduitspfnlView2
     */
    public ViewObjectImpl getProduitspfnlView2() {
        return (ViewObjectImpl) findViewObject("ProduitspfnlView2");
    }

    /**
     * Container's getter for PartiesrecolteesView2.
     * @return PartiesrecolteesView2
     */
    public ViewObjectImpl getPartiesrecolteesView2() {
        return (ViewObjectImpl) findViewObject("PartiesrecolteesView2");
    }

    /**
     * Container's getter for PartiesproduitspfnlView2.
     * @return PartiesproduitspfnlView2
     */
    public ViewObjectImpl getPartiesproduitspfnlView2() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView2");
    }

    /**
     * Container's getter for FamillepfnlView2.
     * @return FamillepfnlView2
     */
    public ViewObjectImpl getFamillepfnlView2() {
        return (ViewObjectImpl) findViewObject("FamillepfnlView2");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView3.
     * @return PartiesProduitsPfnlView3
     */
    public ViewObjectImpl getPartiesProduitsPfnlView3() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView3");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView4.
     * @return PartiesProduitsPfnlView4
     */
    public ViewObjectImpl getPartiesProduitsPfnlView4() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView4");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView5.
     * @return PartiesProduitsPfnlView5
     */
    public ViewObjectImpl getPartiesProduitsPfnlView5() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView5");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView6.
     * @return PartiesProduitsPfnlView6
     */
    public ViewObjectImpl getPartiesProduitsPfnlView6() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView6");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView7.
     * @return PartiesProduitsPfnlView7
     */
    public ViewObjectImpl getPartiesProduitsPfnlView7() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView7");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView8.
     * @return PartiesProduitsPfnlView8
     */
    public ViewObjectImpl getPartiesProduitsPfnlView8() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView8");
    }

    /**
     * Container's getter for ProduitsPfnlView3.
     * @return ProduitsPfnlView3
     */
    public ViewObjectImpl getProduitsPfnlView3() {
        return (ViewObjectImpl) findViewObject("ProduitsPfnlView3");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView9.
     * @return PartiesProduitsPfnlView9
     */
    public ViewObjectImpl getPartiesProduitsPfnlView9() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView9");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView10.
     * @return PartiesProduitsPfnlView10
     */
    public ViewObjectImpl getPartiesProduitsPfnlView10() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView10");
    }

    /**
     * Container's getter for ProduitsPfnlView4.
     * @return ProduitsPfnlView4
     */
    public ViewObjectImpl getProduitsPfnlView4() {
        return (ViewObjectImpl) findViewObject("ProduitsPfnlView4");
    }

    /**
     * Container's getter for ProduitsPfnlView5.
     * @return ProduitsPfnlView5
     */
    public ViewObjectImpl getProduitsPfnlView5() {
        return (ViewObjectImpl) findViewObject("ProduitsPfnlView5");
    }

    /**
     * Container's getter for ProduitsPfnlView6.
     * @return ProduitsPfnlView6
     */
    public ViewObjectImpl getProduitsPfnlView6() {
        return (ViewObjectImpl) findViewObject("ProduitsPfnlView6");
    }

    /**
     * Container's getter for ProduitspfnlView7.
     * @return ProduitspfnlView7
     */
    public ViewObjectImpl getProduitspfnlView7() {
        return (ViewObjectImpl) findViewObject("ProduitspfnlView7");
    }

    /**
     * Container's getter for PartiesproduitspfnlView11.
     * @return PartiesproduitspfnlView11
     */
    public ViewObjectImpl getPartiesproduitspfnlView11() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView11");
    }

    /**
     * Container's getter for PartiesproduitspfnlView12.
     * @return PartiesproduitspfnlView12
     */
    public ViewObjectImpl getPartiesproduitspfnlView12() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView12");
    }

    /**
     * Container's getter for ProduitspfnlView8.
     * @return ProduitspfnlView8
     */
    public ViewObjectImpl getProduitspfnlView8() {
        return (ViewObjectImpl) findViewObject("ProduitspfnlView8");
    }

    /**
     * Container's getter for PartiesproduitspfnlView13.
     * @return PartiesproduitspfnlView13
     */
    public ViewObjectImpl getPartiesproduitspfnlView13() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView13");
    }

    /**
     * Container's getter for PartiesproduitspfnlView14.
     * @return PartiesproduitspfnlView14
     */
    public ViewObjectImpl getPartiesproduitspfnlView14() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView14");
    }

    /**
     * Container's getter for ProduitspfnlView9.
     * @return ProduitspfnlView9
     */
    public ViewObjectImpl getProduitspfnlView9() {
        return (ViewObjectImpl) findViewObject("ProduitspfnlView9");
    }

    /**
     * Container's getter for PartiesproduitspfnlView15.
     * @return PartiesproduitspfnlView15
     */
    public ViewObjectImpl getPartiesproduitspfnlView15() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView15");
    }

    /**
     * Container's getter for PartiesproduitspfnlView16.
     * @return PartiesproduitspfnlView16
     */
    public ViewObjectImpl getPartiesproduitspfnlView16() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView16");
    }

    /**
     * Container's getter for ProduitspfnlView10.
     * @return ProduitspfnlView10
     */
    public ViewObjectImpl getProduitspfnlView10() {
        return (ViewObjectImpl) findViewObject("ProduitspfnlView10");
    }

    /**
     * Container's getter for PartiesproduitspfnlView17.
     * @return PartiesproduitspfnlView17
     */
    public ViewObjectImpl getPartiesproduitspfnlView17() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView17");
    }

    /**
     * Container's getter for PartiesproduitspfnlView18.
     * @return PartiesproduitspfnlView18
     */
    public ViewObjectImpl getPartiesproduitspfnlView18() {
        return (ViewObjectImpl) findViewObject("PartiesproduitspfnlView18");
    }

    /**
     * Container's getter for PartiesProduitsPfnlView19.
     * @return PartiesProduitsPfnlView19
     */
    public ViewObjectImpl getPartiesProduitsPfnlView19() {
        return (ViewObjectImpl) findViewObject("PartiesProduitsPfnlView19");
    }

    /**
     * Container's getter for DepartementsIbfk1Link1.
     * @return DepartementsIbfk1Link1
     */
    public ViewLinkImpl getDepartementsIbfk1Link1() {
        return (ViewLinkImpl) findViewLink("DepartementsIbfk1Link1");
    }

    /**
     * Container's getter for DepartementsIbfk1Assoc1Link1.
     * @return DepartementsIbfk1Assoc1Link1
     */
    public ViewLinkImpl getDepartementsIbfk1Assoc1Link1() {
        return (ViewLinkImpl) findViewLink("DepartementsIbfk1Assoc1Link1");
    }

    /**
     * Container's getter for CommunesIbfk1Link1.
     * @return CommunesIbfk1Link1
     */
    public ViewLinkImpl getCommunesIbfk1Link1() {
        return (ViewLinkImpl) findViewLink("CommunesIbfk1Link1");
    }

    /**
     * Container's getter for DepartementsIbfk1Assoc2Link1.
     * @return DepartementsIbfk1Assoc2Link1
     */
    public ViewLinkImpl getDepartementsIbfk1Assoc2Link1() {
        return (ViewLinkImpl) findViewLink("DepartementsIbfk1Assoc2Link1");
    }

    /**
     * Container's getter for CommunesIbfk1Assoc1Link1.
     * @return CommunesIbfk1Assoc1Link1
     */
    public ViewLinkImpl getCommunesIbfk1Assoc1Link1() {
        return (ViewLinkImpl) findViewLink("CommunesIbfk1Assoc1Link1");
    }

    /**
     * Container's getter for CommunesIbfk1Assoc2Link1.
     * @return CommunesIbfk1Assoc2Link1
     */
    public ViewLinkImpl getCommunesIbfk1Assoc2Link1() {
        return (ViewLinkImpl) findViewLink("CommunesIbfk1Assoc2Link1");
    }

    /**
     * Container's getter for CommunesIbfk1Link2.
     * @return CommunesIbfk1Link2
     */
    public ViewLinkImpl getCommunesIbfk1Link2() {
        return (ViewLinkImpl) findViewLink("CommunesIbfk1Link2");
    }

    /**
     * Container's getter for DepartementsIbfk1Link2.
     * @return DepartementsIbfk1Link2
     */
    public ViewLinkImpl getDepartementsIbfk1Link2() {
        return (ViewLinkImpl) findViewLink("DepartementsIbfk1Link2");
    }

    /**
     * Container's getter for CommunesIbfk1Link1_1.
     * @return CommunesIbfk1Link1_1
     */
    public ViewLinkImpl getCommunesIbfk1Link1_1() {
        return (ViewLinkImpl) findViewLink("CommunesIbfk1Link1_1");
    }

    /**
     * Container's getter for DepartementsIbfk1Link1_1.
     * @return DepartementsIbfk1Link1_1
     */
    public ViewLinkImpl getDepartementsIbfk1Link1_1() {
        return (ViewLinkImpl) findViewLink("DepartementsIbfk1Link1_1");
    }

    /**
     * Container's getter for CommunesIbfk1Link2_1.
     * @return CommunesIbfk1Link2_1
     */
    public ViewLinkImpl getCommunesIbfk1Link2_1() {
        return (ViewLinkImpl) findViewLink("CommunesIbfk1Link2_1");
    }

    /**
     * Container's getter for DepartementsIbfk1Link2_1.
     * @return DepartementsIbfk1Link2_1
     */
    public ViewLinkImpl getDepartementsIbfk1Link2_1() {
        return (ViewLinkImpl) findViewLink("DepartementsIbfk1Link2_1");
    }

    /**
     * Container's getter for CommunesIbfk1Assoc2Link2.
     * @return CommunesIbfk1Assoc2Link2
     */
    public ViewLinkImpl getCommunesIbfk1Assoc2Link2() {
        return (ViewLinkImpl) findViewLink("CommunesIbfk1Assoc2Link2");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Link1.
     * @return FkPartiesproduitspfnl2Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Link1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Link1.
     * @return FkPartiesproduitspfnl1Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Link1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Assoc1Link1.
     * @return FkPartiesproduitspfnl2Assoc1Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Assoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Assoc1Link1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Assoc1Link1.
     * @return FkPartiesproduitspfnl1Assoc1Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Assoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Assoc1Link1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Assoc2Link1.
     * @return FkPartiesproduitspfnl2Assoc2Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Assoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Assoc2Link1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Assoc2Link1.
     * @return FkPartiesproduitspfnl1Assoc2Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Assoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Assoc2Link1");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Link1.
     * @return ProduitspfnlIbfk1Link1
     */
    public ViewLinkImpl getProduitspfnlIbfk1Link1() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Link1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Assoc3Link1.
     * @return FkPartiesproduitspfnl2Assoc3Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Assoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Assoc3Link1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Assoc3Link1.
     * @return FkPartiesproduitspfnl1Assoc3Link1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Assoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Assoc3Link1");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Assoc1Link1.
     * @return ProduitspfnlIbfk1Assoc1Link1
     */
    public ViewLinkImpl getProduitspfnlIbfk1Assoc1Link1() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Assoc1Link1");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Assoc2Link1.
     * @return ProduitspfnlIbfk1Assoc2Link1
     */
    public ViewLinkImpl getProduitspfnlIbfk1Assoc2Link1() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Assoc2Link1");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Assoc3Link1.
     * @return ProduitspfnlIbfk1Assoc3Link1
     */
    public ViewLinkImpl getProduitspfnlIbfk1Assoc3Link1() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Assoc3Link1");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Link2.
     * @return ProduitspfnlIbfk1Link2
     */
    public ViewLinkImpl getProduitspfnlIbfk1Link2() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Link2");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Link2.
     * @return FkPartiesproduitspfnl1Link2
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Link2() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Link2");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Link2.
     * @return FkPartiesproduitspfnl2Link2
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Link2() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Link2");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Link1_1.
     * @return ProduitspfnlIbfk1Link1_1
     */
    public ViewLinkImpl getProduitspfnlIbfk1Link1_1() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Link1_1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Link1_1.
     * @return FkPartiesproduitspfnl1Link1_1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Link1_1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Link1_1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Link1_1.
     * @return FkPartiesproduitspfnl2Link1_1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Link1_1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Link1_1");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Link2_1.
     * @return ProduitspfnlIbfk1Link2_1
     */
    public ViewLinkImpl getProduitspfnlIbfk1Link2_1() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Link2_1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Link2_1.
     * @return FkPartiesproduitspfnl1Link2_1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Link2_1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Link2_1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Link2_1.
     * @return FkPartiesproduitspfnl2Link2_1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Link2_1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Link2_1");
    }

    /**
     * Container's getter for ProduitspfnlIbfk1Link3_1.
     * @return ProduitspfnlIbfk1Link3_1
     */
    public ViewLinkImpl getProduitspfnlIbfk1Link3_1() {
        return (ViewLinkImpl) findViewLink("ProduitspfnlIbfk1Link3_1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Link3_1.
     * @return FkPartiesproduitspfnl1Link3_1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Link3_1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Link3_1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl2Link3_1.
     * @return FkPartiesproduitspfnl2Link3_1
     */
    public ViewLinkImpl getFkPartiesproduitspfnl2Link3_1() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl2Link3_1");
    }

    /**
     * Container's getter for FkPartiesproduitspfnl1Assoc3Link2.
     * @return FkPartiesproduitspfnl1Assoc3Link2
     */
    public ViewLinkImpl getFkPartiesproduitspfnl1Assoc3Link2() {
        return (ViewLinkImpl) findViewLink("FkPartiesproduitspfnl1Assoc3Link2");
    }

    /**
     * Container's getter for getLastIdRegions1.
     * @return getLastIdRegions1
     */
    public getLastIdRegionsImpl getgetLastIdRegions1() {
        return (getLastIdRegionsImpl) findViewObject("getLastIdRegions1");
    }

    /**
     * Container's getter for getLastIdDepartements1.
     * @return getLastIdDepartements1
     */
    public getLastIdDepartementsImpl getgetLastIdDepartements1() {
        return (getLastIdDepartementsImpl) findViewObject("getLastIdDepartements1");
    }

    /**
     * Container's getter for getLastIdCommunes1.
     * @return getLastIdCommunes1
     */
    public getLastIdCommunesImpl getgetLastIdCommunes1() {
        return (getLastIdCommunesImpl) findViewObject("getLastIdCommunes1");
    }

    /**
     * Container's getter for getLastIdFamilles1.
     * @return getLastIdFamilles1
     */
    public getLastIdFamillesImpl getgetLastIdFamilles1() {
        return (getLastIdFamillesImpl) findViewObject("getLastIdFamilles1");
    }

    /**
     * Container's getter for getLastIdProduits1.
     * @return getLastIdProduits1
     */
    public getLastIdProduitsImpl getgetLastIdProduits1() {
        return (getLastIdProduitsImpl) findViewObject("getLastIdProduits1");
    }

    /**
     * Container's getter for getLastIdPartiesRecoltees1.
     * @return getLastIdPartiesRecoltees1
     */
    public getLastIdPartiesRecolteesImpl getgetLastIdPartiesRecoltees1() {
        return (getLastIdPartiesRecolteesImpl) findViewObject("getLastIdPartiesRecoltees1");
    }

    /**
     * Container's getter for getLastIdartiesProduitsPfnl1.
     * @return getLastIdartiesProduitsPfnl1
     */
    public getLastIdartiesProduitsPfnlImpl getgetLastIdartiesProduitsPfnl1() {
        return (getLastIdartiesProduitsPfnlImpl) findViewObject("getLastIdartiesProduitsPfnl1");
    }

    /**
     * Container's getter for PaysView1.
     * @return PaysView1
     */
    public ViewObjectImpl getPaysView1() {
        return (ViewObjectImpl) findViewObject("PaysView1");
    }

    /**
     * Container's getter for PaysView1_1.
     * @return PaysView1_1
     */
    public ViewObjectImpl getPaysView1_1() {
        return (ViewObjectImpl) findViewObject("PaysView1_1");
    }

    /**
     * Container's getter for getLastIdPays1.
     * @return getLastIdPays1
     */
    public getLastIdPaysImpl getgetLastIdPays1() {
        return (getLastIdPaysImpl) findViewObject("getLastIdPays1");
    }

    /**
     * Container's getter for OriginespnflsView1.
     * @return OriginespnflsView1
     */
    public ViewObjectImpl getOriginespnflsView1() {
        return (ViewObjectImpl) findViewObject("OriginespnflsView1");
    }

    /**
     * Container's getter for OriginespnflsView1_1.
     * @return OriginespnflsView1_1
     */
    public ViewObjectImpl getOriginespnflsView1_1() {
        return (ViewObjectImpl) findViewObject("OriginespnflsView1_1");
    }

    /**
     * Container's getter for origineView1.
     * @return origineView1
     */
 //   public origineViewImpl getorigineView1() {
 //       return (origineViewImpl) findViewObject("origineView1");
 //   }

    /**
     * Container's getter for listeOrigine1.
     * @return listeOrigine1
     */
    public listeOrigineImpl getlisteOrigine1() {
        return (listeOrigineImpl) findViewObject("listeOrigine1");
    }

    /**
     * Container's getter for getLastIdOriginePfnl1.
     * @return getLastIdOriginePfnl1
     */
    public getLastIdOriginePfnlImpl getgetLastIdOriginePfnl1() {
        return (getLastIdOriginePfnlImpl) findViewObject("getLastIdOriginePfnl1");
    }

    /**
     * Container's getter for AgrementsView1.
     * @return AgrementsView1
     */
    public ViewObjectImpl getAgrementsView1() {
        return (ViewObjectImpl) findViewObject("AgrementsView1");
    }

    /**
     * Container's getter for PermissionnairespnflView1.
     * @return PermissionnairespnflView1
     */
    public ViewObjectImpl getPermissionnairespnflView1() {
        return (ViewObjectImpl) findViewObject("PermissionnairespnflView1");
    }

    /**
     * Container's getter for PermissionnairespnflView1_1.
     * @return PermissionnairespnflView1_1
     */
    public ViewObjectImpl getPermissionnairespnflView1_1() {
        return (ViewObjectImpl) findViewObject("PermissionnairespnflView1_1");
    }

    /**
     * Container's getter for AgrementsView1_1.
     * @return AgrementsView1_1
     */
    public ViewObjectImpl getAgrementsView1_1() {
        return (ViewObjectImpl) findViewObject("AgrementsView1_1");
    }


    /**
     * Container's getter for listeExploitant1.
     * @return listeExploitant1
     */
    public listeExploitantImpl getlisteExploitant1() {
        return (listeExploitantImpl) findViewObject("listeExploitant1");
    }

    /**
     * Container's getter for listeQualitePermissionnaire1.
     * @return listeQualitePermissionnaire1
     */
    public listeQualitePermissionnaireImpl getlisteQualitePermissionnaire1() {
        return (listeQualitePermissionnaireImpl) findViewObject("listeQualitePermissionnaire1");
    }

    /**
     * Container's getter for listeTypePersonne1.
     * @return listeTypePersonne1
     */
    public listeTypePersonneImpl getlisteTypePersonne1() {
        return (listeTypePersonneImpl) findViewObject("listeTypePersonne1");
    }

    /**
     * Container's getter for listeSexe1.
     * @return listeSexe1
     */
    public listeSexeImpl getlisteSexe1() {
        return (listeSexeImpl) findViewObject("listeSexe1");
    }

    /**
     * Container's getter for listeStatutPermissionnaire1.
     * @return listeStatutPermissionnaire1
     */
    public listeStatutPermissionnaireImpl getlisteStatutPermissionnaire1() {
        return (listeStatutPermissionnaireImpl) findViewObject("listeStatutPermissionnaire1");
    }

    /**
     * Container's getter for getLastIdPermissionnairePfnl1.
     * @return getLastIdPermissionnairePfnl1
     */
    public getLastIdPermissionnairePfnlImpl getgetLastIdPermissionnairePfnl1() {
        return (getLastIdPermissionnairePfnlImpl) findViewObject("getLastIdPermissionnairePfnl1");
    }

    /**
     * Container's getter for CategorieunitemesureView1.
     * @return CategorieunitemesureView1
     */
    public ViewObjectImpl getCategorieunitemesureView1() {
        return (ViewObjectImpl) findViewObject("CategorieunitemesureView1");
    }

    /**
     * Container's getter for CategorieunitemesureView1_1.
     * @return CategorieunitemesureView1_1
     */
    public ViewObjectImpl getCategorieunitemesureView1_1() {
        return (ViewObjectImpl) findViewObject("CategorieunitemesureView1_1");
    }

    /**
     * Container's getter for getLastIdCategorieMesure1.
     * @return getLastIdCategorieMesure1
     */
    public getLastIdCategorieMesureImpl getgetLastIdCategorieMesure1() {
        return (getLastIdCategorieMesureImpl) findViewObject("getLastIdCategorieMesure1");
    }

    /**
     * Container's getter for getLastIdCategorieUniteMesure1.
     * @return getLastIdCategorieUniteMesure1
     */
    public getLastIdCategorieUniteMesureImpl getgetLastIdCategorieUniteMesure1() {
        return (getLastIdCategorieUniteMesureImpl) findViewObject("getLastIdCategorieUniteMesure1");
    }

    /**
     * Container's getter for UnitemesureView1.
     * @return UnitemesureView1
     */
    public ViewObjectImpl getUnitemesureView1() {
        return (ViewObjectImpl) findViewObject("UnitemesureView1");
    }

    /**
     * Container's getter for UnitemesureView1_1.
     * @return UnitemesureView1_1
     */
    public ViewObjectImpl getUnitemesureView1_1() {
        return (ViewObjectImpl) findViewObject("UnitemesureView1_1");
    }

    /**
     * Container's getter for UnitemesureView2.
     * @return UnitemesureView2
     */
    public ViewObjectImpl getUnitemesureView2() {
        return (ViewObjectImpl) findViewObject("UnitemesureView2");
    }

    /**
     * Container's getter for UnitemesureView1_2.
     * @return UnitemesureView1_2
     */
    public ViewObjectImpl getUnitemesureView1_2() {
        return (ViewObjectImpl) findViewObject("UnitemesureView1_2");
    }

    /**
     * Container's getter for FkUnitemesure1Link1.
     * @return FkUnitemesure1Link1
     */
    public ViewLinkImpl getFkUnitemesure1Link1() {
        return (ViewLinkImpl) findViewLink("FkUnitemesure1Link1");
    }

    /**
     * Container's getter for FkUnitemesure1Link2.
     * @return FkUnitemesure1Link2
     */
    public ViewLinkImpl getFkUnitemesure1Link2() {
        return (ViewLinkImpl) findViewLink("FkUnitemesure1Link2");
    }

    /**
     * Container's getter for CategorieunitemesureView2.
     * @return CategorieunitemesureView2
     */
    public ViewObjectImpl getCategorieunitemesureView2() {
        return (ViewObjectImpl) findViewObject("CategorieunitemesureView2");
    }


    /**
     * Container's getter for CategorieunitemesureView3.
     * @return CategorieunitemesureView3
     */
    public ViewObjectImpl getCategorieunitemesureView3() {
        return (ViewObjectImpl) findViewObject("CategorieunitemesureView3");
    }


    /**
     * Container's getter for CategorieunitemesureView4.
     * @return CategorieunitemesureView4
     */
    public ViewObjectImpl getCategorieunitemesureView4() {
        return (ViewObjectImpl) findViewObject("CategorieunitemesureView4");
    }

    /**
     * Container's getter for UnitemesureView3.
     * @return UnitemesureView3
     */
    public ViewObjectImpl getUnitemesureView3() {
        return (ViewObjectImpl) findViewObject("UnitemesureView3");
    }

    /**
     * Container's getter for CategToUnitLink.
     * @return CategToUnitLink
     */
    public ViewLinkImpl getCategToUnitLink() {
        return (ViewLinkImpl) findViewLink("CategToUnitLink");
    }

    /**
     * Container's getter for CategorieunitemesureView5.
     * @return CategorieunitemesureView5
     */
    public ViewObjectImpl getCategorieunitemesureView5() {
        return (ViewObjectImpl) findViewObject("CategorieunitemesureView5");
    }

    /**
     * Container's getter for CategToUnitLink1.
     * @return CategToUnitLink1
     */
    public ViewLinkImpl getCategToUnitLink1() {
        return (ViewLinkImpl) findViewLink("CategToUnitLink1");
    }

    /**
     * Container's getter for UnitemesureView4.
     * @return UnitemesureView4
     */
    public ViewObjectImpl getUnitemesureView4() {
        return (ViewObjectImpl) findViewObject("UnitemesureView4");
    }

    /**
     * Container's getter for CategToUnitLink2.
     * @return CategToUnitLink2
     */
    public ViewLinkImpl getCategToUnitLink2() {
        return (ViewLinkImpl) findViewLink("CategToUnitLink2");
    }

    /**
     * Container's getter for CategorieunitemesureView6.
     * @return CategorieunitemesureView6
     */
    public ViewObjectImpl getCategorieunitemesureView6() {
        return (ViewObjectImpl) findViewObject("CategorieunitemesureView6");
    }

    /**
     * Container's getter for gestLastIdUnitMesure1.
     * @return gestLastIdUnitMesure1
     */
    public gestLastIdUnitMesureImpl getgetLastIdUnitMesure1() {
        return (gestLastIdUnitMesureImpl) findViewObject("getLastIdUnitMesure1");
    }

    /**
     * Container's getter for listOrdreGrandeur1.
     * @return listOrdreGrandeur1
     */
    public listOrdreGrandeurImpl getlistOrdreGrandeur1() {
        return (listOrdreGrandeurImpl) findViewObject("listOrdreGrandeur1");
    }
}

