package cm.gov.minfof.model.entity;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 29 11:20:17 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartiesProduitsPfnlViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_PARTIESPRODUITSPFNL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idpartiesproduitspfnl,
        Idpartiesrecoltees,
        Idproduitspfnl,
        Estunproduitpfnl,
        estUnProduitPfnlTransient,
        PartiesProduitsPfnlView,
        PartiesProduitsPfnlView1,
        ProduitsPfnlView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDPARTIESPRODUITSPFNL = AttributesEnum.Idpartiesproduitspfnl.index();
    public static final int IDPARTIESRECOLTEES = AttributesEnum.Idpartiesrecoltees.index();
    public static final int IDPRODUITSPFNL = AttributesEnum.Idproduitspfnl.index();
    public static final int ESTUNPRODUITPFNL = AttributesEnum.Estunproduitpfnl.index();
    public static final int ESTUNPRODUITPFNLTRANSIENT = AttributesEnum.estUnProduitPfnlTransient.index();
    public static final int PARTIESPRODUITSPFNLVIEW = AttributesEnum.PartiesProduitsPfnlView.index();
    public static final int PARTIESPRODUITSPFNLVIEW1 = AttributesEnum.PartiesProduitsPfnlView1.index();
    public static final int PRODUITSPFNLVIEW = AttributesEnum.ProduitsPfnlView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PartiesProduitsPfnlViewRowImpl() {
    }

    /**
     * Gets PartiesProduitsPfnl entity object.
     * @return the PartiesProduitsPfnl
     */
    public EntityImpl getPartiesProduitsPfnl() {
        return (EntityImpl) getEntity(ENTITY_PARTIESPRODUITSPFNL);
    }

    /**
     * Gets the attribute value for idpartiesproduitspfnl using the alias name Idpartiesproduitspfnl.
     * @return the idpartiesproduitspfnl
     */
    public BigDecimal getIdpartiesproduitspfnl() {
        return (BigDecimal) getAttributeInternal(IDPARTIESPRODUITSPFNL);
    }

    /**
     * Sets <code>value</code> as attribute value for idpartiesproduitspfnl using the alias name Idpartiesproduitspfnl.
     * @param value value to set the idpartiesproduitspfnl
     */
    public void setIdpartiesproduitspfnl(BigDecimal value) {
        setAttributeInternal(IDPARTIESPRODUITSPFNL, value);
    }

    /**
     * Gets the attribute value for idpartiesrecoltees using the alias name Idpartiesrecoltees.
     * @return the idpartiesrecoltees
     */
    public BigDecimal getIdpartiesrecoltees() {
        return (BigDecimal) getAttributeInternal(IDPARTIESRECOLTEES);
    }

    /**
     * Sets <code>value</code> as attribute value for idpartiesrecoltees using the alias name Idpartiesrecoltees.
     * @param value value to set the idpartiesrecoltees
     */
    public void setIdpartiesrecoltees(BigDecimal value) {
        setAttributeInternal(IDPARTIESRECOLTEES, value);
    }

    /**
     * Gets the attribute value for idproduitspfnl using the alias name Idproduitspfnl.
     * @return the idproduitspfnl
     */
    public BigDecimal getIdproduitspfnl() {
        return (BigDecimal) getAttributeInternal(IDPRODUITSPFNL);
    }

    /**
     * Sets <code>value</code> as attribute value for idproduitspfnl using the alias name Idproduitspfnl.
     * @param value value to set the idproduitspfnl
     */
    public void setIdproduitspfnl(BigDecimal value) {
        setAttributeInternal(IDPRODUITSPFNL, value);
    }

    /**
     * Gets the attribute value for estunproduitpfnl using the alias name Estunproduitpfnl.
     * @return the estunproduitpfnl
     */
    public Integer getEstunproduitpfnl() {
        return (Integer) getAttributeInternal(ESTUNPRODUITPFNL);
    }

    /**
     * Sets <code>value</code> as attribute value for estunproduitpfnl using the alias name Estunproduitpfnl.
     * @param value value to set the estunproduitpfnl
     */
    public void setEstunproduitpfnl(Integer value) {
        setAttributeInternal(ESTUNPRODUITPFNL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute estUnProduitPfnlTransient.
     * @return the estUnProduitPfnlTransient
     */
    public Boolean getestUnProduitPfnlTransient() {
        try
        {
            if (getEstunproduitpfnl() != 0)
                return true;
            else
                return false;
        }
        catch (NullPointerException e)
        {
            return false;
        }
        //return (Boolean) getAttributeInternal(ESTUNPRODUITPFNLTRANSIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute estUnProduitPfnlTransient.
     * @param value value to set the  estUnProduitPfnlTransient
     */
    public void setestUnProduitPfnlTransient(Boolean value) {
        if (value)
            setAttributeInternal(ESTUNPRODUITPFNL, 1);
        else
            setAttributeInternal(ESTUNPRODUITPFNL, 0);
        //setAttributeInternal(ESTUNPRODUITPFNLTRANSIENT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PartiesProduitsPfnlView.
     */
    public RowIterator getPartiesProduitsPfnlView() {
        return (RowIterator) getAttributeInternal(PARTIESPRODUITSPFNLVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PartiesProduitsPfnlView1.
     */
    public RowIterator getPartiesProduitsPfnlView1() {
        return (RowIterator) getAttributeInternal(PARTIESPRODUITSPFNLVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProduitsPfnlView.
     */
    public RowIterator getProduitsPfnlView() {
        return (RowIterator) getAttributeInternal(PRODUITSPFNLVIEW);
    }
}

