package cm.gov.minfof.model.entityviewobject;

import cm.gov.minfof.model.entity.CollectepfnlImpl;

import cm.gov.minfof.model.entityviewobject.common.CollectepfnlViewRow;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 22 15:09:41 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CollectepfnlViewRowImpl extends ViewRowImpl implements CollectepfnlViewRow {


    public static final int ENTITY_COLLECTEPFNL = 0;

    @Override
    public String getIdentificateur() {
        // TODO Implement this method
        return null;
    }

    @Override
    public void setIdentificateur(String value) {
        // TODO Implement this method
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idcollectepfnl,
        Datecollecte,
        Iddepartement,
        Idlocalite,
        Idposte,
        Idutilisateur,
        CollectepfnlView,
        DetailscollectepfnlView,
        DepartementView1,
        LocaliteView1,
        PostecontroleView1,
        UtilisateurView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDCOLLECTEPFNL = AttributesEnum.Idcollectepfnl.index();
    public static final int DATECOLLECTE = AttributesEnum.Datecollecte.index();
    public static final int IDDEPARTEMENT = AttributesEnum.Iddepartement.index();
    public static final int IDLOCALITE = AttributesEnum.Idlocalite.index();
    public static final int IDPOSTE = AttributesEnum.Idposte.index();
    public static final int IDUTILISATEUR = AttributesEnum.Idutilisateur.index();
    public static final int COLLECTEPFNLVIEW = AttributesEnum.CollectepfnlView.index();
    public static final int DETAILSCOLLECTEPFNLVIEW = AttributesEnum.DetailscollectepfnlView.index();
    public static final int DEPARTEMENTVIEW1 = AttributesEnum.DepartementView1.index();
    public static final int LOCALITEVIEW1 = AttributesEnum.LocaliteView1.index();
    public static final int POSTECONTROLEVIEW1 = AttributesEnum.PostecontroleView1.index();
    public static final int UTILISATEURVIEW1 = AttributesEnum.UtilisateurView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CollectepfnlViewRowImpl() {
    }

    /**
     * Gets Collectepfnl entity object.
     * @return the Collectepfnl
     */
    public CollectepfnlImpl getCollectepfnl() {
        return (CollectepfnlImpl) getEntity(ENTITY_COLLECTEPFNL);
    }

    /**
     * Gets the attribute value for idcollectepfnl using the alias name Idcollectepfnl.
     * @return the idcollectepfnl
     */
    public BigDecimal getIdcollectepfnl() {
        return (BigDecimal) getAttributeInternal(IDCOLLECTEPFNL);
    }

    /**
     * Sets <code>value</code> as attribute value for idcollectepfnl using the alias name Idcollectepfnl.
     * @param value value to set the idcollectepfnl
     */
    public void setIdcollectepfnl(BigDecimal value) {
        setAttributeInternal(IDCOLLECTEPFNL, value);
    }

    /**
     * Gets the attribute value for datecollecte using the alias name Datecollecte.
     * @return the datecollecte
     */
    public Timestamp getDatecollecte() {
        return (Timestamp) getAttributeInternal(DATECOLLECTE);
    }

    /**
     * Sets <code>value</code> as attribute value for datecollecte using the alias name Datecollecte.
     * @param value value to set the datecollecte
     */
    public void setDatecollecte(Timestamp value) {
        setAttributeInternal(DATECOLLECTE, value);
    }


    /**
     * Gets the attribute value for iddepartement using the alias name Iddepartement.
     * @return the iddepartement
     */
    public BigDecimal getIddepartement() {
        return (BigDecimal) getAttributeInternal(IDDEPARTEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for iddepartement using the alias name Iddepartement.
     * @param value value to set the iddepartement
     */
    public void setIddepartement(BigDecimal value) {
        setAttributeInternal(IDDEPARTEMENT, value);
    }


    /**
     * Gets the attribute value for idlocalite using the alias name Idlocalite.
     * @return the idlocalite
     */
    public BigDecimal getIdlocalite() {
        return (BigDecimal) getAttributeInternal(IDLOCALITE);
    }

    /**
     * Sets <code>value</code> as attribute value for idlocalite using the alias name Idlocalite.
     * @param value value to set the idlocalite
     */
    public void setIdlocalite(BigDecimal value) {
        setAttributeInternal(IDLOCALITE, value);
    }

    /**
     * Gets the attribute value for idposte using the alias name Idposte.
     * @return the idposte
     */
    public BigDecimal getIdposte() {
        return (BigDecimal) getAttributeInternal(IDPOSTE);
    }

    /**
     * Sets <code>value</code> as attribute value for idposte using the alias name Idposte.
     * @param value value to set the idposte
     */
    public void setIdposte(BigDecimal value) {
        setAttributeInternal(IDPOSTE, value);
    }

    /**
     * Gets the attribute value for idutilisateur using the alias name Idutilisateur.
     * @return the idutilisateur
     */
    public BigDecimal getIdutilisateur() {
        return (BigDecimal) getAttributeInternal(IDUTILISATEUR);
    }

    /**
     * Sets <code>value</code> as attribute value for idutilisateur using the alias name Idutilisateur.
     * @param value value to set the idutilisateur
     */
    public void setIdutilisateur(BigDecimal value) {
        setAttributeInternal(IDUTILISATEUR, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CollectepfnlView.
     */
    public RowIterator getCollectepfnlView() {
        return (RowIterator) getAttributeInternal(COLLECTEPFNLVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DetailscollectepfnlView.
     */
    public RowIterator getDetailscollectepfnlView() {
        return (RowIterator) getAttributeInternal(DETAILSCOLLECTEPFNLVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepartementView1.
     */
    public RowSet getDepartementView1() {
        return (RowSet) getAttributeInternal(DEPARTEMENTVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LocaliteView1.
     */
    public RowSet getLocaliteView1() {
        return (RowSet) getAttributeInternal(LOCALITEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PostecontroleView1.
     */
    public RowSet getPostecontroleView1() {
        return (RowSet) getAttributeInternal(POSTECONTROLEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UtilisateurView1.
     */
    public RowSet getUtilisateurView1() {
        return (RowSet) getAttributeInternal(UTILISATEURVIEW1);
    }
}

