package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 15 12:06:07 WAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailscollectepfnlViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DetailscollectepfnlViewImpl() {
    }
}

